name: glf
version: 0.2.0
author: david bernard <david.bernard.31@gmail.com>
description: another toolbox for webgl (used by vdrones)
homepage: http://github.com/davidB/glf
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  vector_math: '>=1.4.3'
  html_toolbox: '>=0.2.0'
dev_dependencies:
  asset_pack: '>=0.6.2'
  dartemis_toolbox:
    #path: ../dartemis_toolbox
    git: https://github.com/davidB/dartemis_toolbox.git
    version: '>=0.5.0'
  js: '>=0.2.0 <0.3.0'
  unittest: '>=0.10.0'
